"""Shared protocol and resource limits."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

HOST = os.getenv("CRYPTALINK_HOST", "127.0.0.1")
PORT = int(os.getenv("CRYPTALINK_PORT", "9000"))
REPLAY_WINDOW_SECONDS = 60
MAX_FILE_BYTES = 10 * 1024 * 1024
MAX_FILENAME_BYTES = 255
RSA_BITS = 3072
RSA_KEY_BYTES = RSA_BITS // 8
PACKET_FIXED_OVERHEAD = 4 + 1 + 16 + 8 + 12 + 2 + RSA_KEY_BYTES + 8 + 16 + 2 + 32
MAX_PACKET_BYTES = MAX_FILE_BYTES + MAX_FILENAME_BYTES + PACKET_FIXED_OVERHEAD
SESSION_SECRET_BYTES = 64
AES_KEY_BYTES = 32
HMAC_KEY_BYTES = 32
GCM_NONCE_BYTES = 12
GCM_TAG_BYTES = 16
MESSAGE_ID_BYTES = 16
PROTOCOL_MAGIC = b"CLNK"
PROTOCOL_VERSION = 1
BASE_DIR = Path(__file__).resolve().parent
KEY_DIR = BASE_DIR / "keys"
PRIVATE_KEY_PATH = KEY_DIR / "server_private.pem"
PUBLIC_KEY_PATH = KEY_DIR / "server_public.pem"
RECEIVED_DIR = BASE_DIR / "storage" / "received"
AUDIT_LOG_PATH = BASE_DIR / "storage" / "logs" / "audit.jsonl"
SOCKET_TIMEOUT = 10
STATUS_OK = 0
STATUS_MALFORMED = 1
STATUS_INTEGRITY_FAILED = 2
STATUS_STALE_TIMESTAMP = 3
STATUS_REPLAY = 4
STATUS_DECRYPT_FAILED = 5
STATUS_TOO_LARGE = 6
STATUS_INTERNAL = 7
